### ISSUE TITLE
The ats2-postiats 0.1.6 has build waring on Mac OS X.

### ISSUE THREAD

**Issue by master-q** [githwxi/ATS-Postiats#117]
https://github.com/Homebrew/homebrew/pull/35630

> There's a weird testing error that exists in this version and the one prior:
> 
> ```
> ld: warning: directory not found for option '-L/usr/local/Cellar/ats2-postiats/0.1.6/lib/ats2-postiats-0.1.6/ccomp/atslib/lib64'
> ```
> 
> It's correct, that directory does not exist. But why is it expecting it to in the first place? Moving it to libexec seems to resolve the issue, and create that directory, so we may wish to do that.

**Comment by githwxi** [comment]
Yes, that directory is currently unused. It was meant for some sort of cross-compilation.

**Comment by hborders** [comment]
I just installed with `homebrew` using: `brew install ats2-postiats`, and I tried building [`hello.dats`](http://ats-lang.sourceforge.net/DOCUMENT/INT2PROGINATS/HTML/c44.html#a_running_program) with `patscc -o hello hello.dats`, and I got this warning.

If I run `patscc` alone, I get the following output:
```
ATS/Postiats version 0.3.10 with Copyright (c) 2011-2018 Hongwei Xi
```

**Comment by githwxi** [comment]
What warning did you see?

**Comment by hborders** [comment]
```
$ xcodebuild -version
Xcode 9.3
Build version 9E145

$ brew info ats2-postiats 
ats2-postiats: stable 0.3.10 (bottled)
Programming language with formal specification features
http://www.ats-lang.org/
/usr/local/Cellar/ats2-postiats/0.3.10 (1,689 files, 8.0MB) *
  Poured from bottle on 2018-04-27 at 21:50:39
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ats2-postiats.rb
==> Dependencies
Required: gmp ✔

$ patscc -o hello hello.dats
ld: warning: directory not found for option '-L/usr/local/Cellar/ats2-postiats/0.3.10/lib/ats2-postiats-0.3.9/ccomp/atslib/lib64'

$ ./hello
Hello, world!
```
