### ISSUE TITLE
Compile issue with ATS Github (cygwin 64 build)

### ISSUE THREAD

**Issue by bbarker** [githwxi/ATS-Postiats#120]
I'm guessing this is possibly an issue with my ATS being "too new", but just in case ...:
```
/home/brand_000/ats-lang-anairiats-0.2.11/bin/atsopt -DATS C3NSTRINTKND=gmpknd --output pats_symenv_sats.c --static pats_symenv.sats
/home/brand_000/ATS-Postiats/src/pats_symenv.sats: 1590(line=48, offs=1) -- 1595(line=48, offs=6): error(2): the static identifier [absvt] is unrecognized.
exit(ATS): uncaught exception: ATS_2d0_2e2_2e11_2src_2ats_error_2esats__FatalErrorException(1027)
Makefile:799: recipe for target 'pats_symenv_sats.c' failed
make[1]: *** [pats_symenv_sats.c] Error 1
```

**Comment by githwxi** [comment]
Or your ATS1 is not new enough :)

Try to upgrade your ATS1 to ATS1-0.2.11-fin:

https://sourceforge.net/projects/ats-lang/files/ats-lang/anairiats-0.2.11/

**Comment by bbarker** [comment]
That did it, thanks!

On Mon, Jan 19, 2015 at 6:59 PM, Hongwei Xi <notifications@github.com>
wrote:

> Or your ATS1 is not new enough :)
>
> Try to upgrade your ATS1 to ATS1-0.2.11-fin:
>
> https://sourceforge.net/projects/ats-lang/files/ats-lang/anairiats-0.2.11/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/githwxi/ATS-Postiats/issues/120#issuecomment-70582301>
> .
>



-- 
Brandon Barker
brandon.barker@gmail.com
