### ISSUE TITLE
Improve compatibility for OS X

### ISSUE THREAD

**Issue by cosmo0920** [githwxi/ATS-Postiats#122]
For OS X, there are lack of compatibility.

* Homebrew's gtk+3 pkg-config dose not work correctly with default setting.
  * It needs to install `XQuartz` and add `/opt/X11/lib/pkgconfig` into `PKG_CONFIG_PATH`
* OS X dose not have `pthread_spinlock_t` type. 
  * OS X has [OSSpinlock](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/spinlock.3.html).
* Also `CLOCK_REALTIME` is missing in OS X.
  * OS X does not have `clock_gettime`, use `clock_get_time` instead.
* It seems to be used clang instead of gcc in test under OS X Travis CI worker environment.
  * In test, it also needs specify `CC=${GCC}`? 

  Because, following output is clang style:
```log
mandelbrot_v2df_dats.c:224:10: error: use of unknown builtin '__builtin_ia32_cmplepd' [-Wimplicit-function-declaration]
lte2 = __builtin_ia32_cmplepd(x, y) ;
       ^
mandelbrot_v2df_dats.c:224:8: error: assigning to 'v2df' from incompatible type 'int'
lte2 = __builtin_ia32_cmplepd(x, y) ;
     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2 errors generated.
```

**Comment by githwxi** [comment]
Thank you very much1

I have just created a repository of the name ATS-Postiats-test.

My plan is to move most of the testing to ATS-Postiats-test. The testing
at ATS-Postiats can then be kept to be Linux-specific.

**Comment by cosmo0920** [comment]
> I have just created a repository of the name ATS-Postiats-test.

Thank you so much!

I've seen that repository.  I'm surprised to your fast work! XD

> My plan is to move most of the testing to ATS-Postiats-test. The testing
at ATS-Postiats can then be kept to be Linux-specific. 

You mean that this repository's test keep only Linux-specific and move OSX-specific test to ATS-Postiats-test repository, right?

Hmm, I have a question.
ATS-postiats will accepts OSX-specific implementation and patches?

**Comment by githwxi** [comment]
>>You mean that this repository's test keep only Linux-specific and move OSX-specific test to ATS-Postiats-test repository, right?

Gradually, I hope that most of testing (even testing for Linux) can be moved to ATS-Postiats-test. In particular, I would like to invite ats-lang-users community to contribute code for testing.

>> ATS-postiats will accepts OSX-specific implementation and patches?

Certainly!  For the time being, I would like to put OSX-specific code in ATS-Postiats-contrib.
More specifically, in a place like:

ATS-Postiats-contrib/contrib/macosx

**Comment by githwxi** [comment]
I add an example involving clock_gettime (for linux):

https://github.com/githwxi/ATS-Postiats-test/blob/master/contrib/test-hwxi/test01.dats

Could you create a version (test01-osx.dats) for use under OSX?

**Comment by cosmo0920** [comment]
> Could you create a version (test01-osx.dats) for use under OSX?

OK, I'll try it!
But, I'm newbie of ATS2 lang... :< 


I'll do the best that I can.

**Comment by githwxi** [comment]
Everyone was a newbie of something at some point :)

You could just write C code if you like. I do not have access to a mac machine.
But I can readily turn C code into ATS code and then uses travis-CI to test the ATS code.

**Comment by cosmo0920** [comment]
Sorry for late response.
Simply `clock_get_time()` usage for OSX (C version) is like this:

```c
#include <mach/mach.h>
#include <mach/clock.h>
#include <mach/mach_error.h>
#include <stdio.h>
#include <stdlib.h>

int main(void) {
  kern_return_t ret;
  clock_serv_t mach_clock;
  mach_timespec_t mach_time;

  ret = host_get_clock_service(mach_host_self(), CALENDAR_CLOCK,
                               &mach_clock);
  if (ret != KERN_SUCCESS) {
    fprintf(stderr, "host_get_clock_service() failed: %s\n",
            mach_error_string(ret));
    abort();
  }
  ret = clock_get_time(mach_clock, &mach_time);
  if (ret != KERN_SUCCESS) {
    fprintf(stderr, "clock_get_time() failed: %s\n",
            mach_error_string(ret));
    abort();
  }
  printf("mach_time = { %u, %u }\n", mach_time.tv_sec, mach_time.tv_nsec);
  return 0;
}
```

**Comment by githwxi** [comment]
Thanks!

I also tried mach_absolute_time:

https://github.com/githwxi/ATS-Postiats-test/blob/master/contrib/test-hwxi/test01-osx.dats

**Comment by cosmo0920** [comment]
Thanks! I've confirmed that [test01-osx.dats](https://github.com/githwxi/ATS-Postiats-test/blob/master/contrib/hwxi/TEST0/test01-osx.dats) can build under OS X Mavericks environment!!

**Comment by githwxi** [comment]
For the record, the following two items are yet to be handled:

######
Homebrew's gtk+3 pkg-config dose not work correctly with default setting.
    It needs to install XQuartz and add /opt/X11/lib/pkgconfig into PKG_CONFIG_PATH
######
OS X dose not have pthread_spinlock_t type.
    OS X has OSSpinlock.
######

**Comment by cosmo0920** [comment]
Yes, we should do more work for solving this issue.

**Comment by cosmo0920** [comment]
For now, there is only problem:

* OS X dose not have pthread_spinlock_t type.
  +  OS X has OSSpinlock.

**Comment by cosmo0920** [comment]
> OS X dose not have pthread_spinlock_t type. 

Now, ATS-postiats-test repository has [OSSpinLock test](https://github.com/githwxi/ATS-Postiats-test/blob/230448f295c8585ac93916f5b07d846d6a01a4c8/contrib/hwxi/TEST0/OSSpinLock-osx.dats) for OS X.

This issue is solved? Or, it is still remaining things for solving this issue?
I think this issue is NOT solved, because `pthread_spinlock_t` type used in https://github.com/githwxi/ATS-Postiats/blob/f3e9b647da3974a2d83962c0e0304a9bc754f09f/libats/DATS/athread_posix.dats

**Comment by master-q** [comment]
I'm reading GHC git://git.haskell.org/ghc.git. They re-implement own spinlock API on pthread API.

http://git.haskell.org/ghc.git/blob/HEAD:/includes/rts/SpinLock.h

**Comment by githwxi** [comment]
It is not done yet. I added OSSpinLock-osx to just test how OSSpinLock works.
