### ISSUE TITLE
Could you release ats2-mode.el at next version?

### ISSUE THREAD

**Issue by master-q** [githwxi/ATS-Postiats#124]
Could you release ats2-mode.el at next version?

This git repo has ats2 mode for Emacs. However, I think the release tar ball doesn't.

```
$ find ATS-Postiats -name "*.el"
ATS-Postiats/utils/emacs/ats2-mode.el
ATS-Postiats/utils/emacs/ats2-flymake.el
```

I would like to create Debian package "ats2-mode".

**Comment by githwxi** [comment]
Done. It will be available in the next release.
