### ISSUE TITLE
Type-influencer can't know the type of conditional branch?

### ISSUE THREAD

**Issue by master-q** [githwxi/ATS-Postiats#128]
Following code occurs compile error.

```ocaml
#include "share/atspre_staload.hats"

fun f (x:int): int = 10 + x * (if x < 30 then 10 else 100)

implement main0 () = println! (f 20)
```

```shell
$ patscc no_duplicate_code.dats
/home/kiwamu/doc/ATS_Foundations/source/code/conditional/no_duplicate_code.dats: 97(line=4, offs=27) -- 128(line=4, offs=58): error(3): the symbol [*] cannot be resolved due to too many matches:
D2ITMcst(mul_int_double) of 0
D2ITMcst(mul_int_float) of 0
/home/kiwamu/doc/ATS_Foundations/source/code/conditional/no_duplicate_code.dats: 97(line=4, offs=27) -- 128(line=4, offs=58): error(3): the dynamic expression cannot be assigned the type [S2Eapp(S2Ecst(g1uint_int_t0ype); S2Ecst(size_kind), S2EVar(4143))].
/home/kiwamu/doc/ATS_Foundations/source/code/conditional/no_duplicate_code.dats: 97(line=4, offs=27) -- 128(line=4, offs=58): error(3): mismatch of static terms (tyleq):
The actual term is: S2Eerr()
The needed term is: S2Eapp(S2Ecst(g1uint_int_t0ype); S2Ecst(size_kind), S2EVar(4143))
/home/kiwamu/doc/ATS_Foundations/source/code/conditional/no_duplicate_code.dats: 92(line=4, offs=22) -- 128(line=4, offs=58): error(3): the dynamic expression cannot be assigned the type [S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind))].
/home/kiwamu/doc/ATS_Foundations/source/code/conditional/no_duplicate_code.dats: 92(line=4, offs=22) -- 128(line=4, offs=58): error(3): mismatch of static terms (tyleq):
The actual term is: S2Eapp(S2Ecst(g1uint_int_t0ype); S2Ecst(size_kind), S2Eapp(S2Ecst(add_int_int); S2EVar(4142->S2Eintinf(10)), S2EVar(4143)))
The needed term is: S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind))
patsopt(TRANS3): there are [3] errors in total.
exit(ATS): uncaught exception: _2home_2kiwamu_2src_2ATS_2dPostiats_2src_2pats_error_2esats__FatalErrorExn(1025)
```

Type-influencer can't know the type of conditional branch?

**Comment by bbarker** [comment]
I think you can do it manually by saying;

fun f (x:int): int = 10 + x * (if x < 30 then 10 else 100):int

In principle you could be returning an indexed integer type i suppose,
which may be the problem here. I'm having my own problems:


$ patscc testn.dats
/home/brand_000/share/atspre_staload.hats: 1338(line=72, offs=1) --
1390(line=72, offs=53): error(1): the file
[{$PATSPRE}/DATS/list_vt_mergesort.dats] is not available for
staloading.
/home/brand_000/share/atspre_staload.hats: 1391(line=73, offs=1) --
1443(line=73, offs=53): error(1): the file
[{$PATSPRE}/DATS/list_vt_quicksort.dats] is not available for
staloading.
/home/brand_000/share/atspre_staload.hats: 1624(line=83, offs=1) --
1672(line=83, offs=49): error(1): the file
[{$PATSPRE}/DATS/array_bsearch.dats] is not available for staloading.
/home/brand_000/share/atspre_staload.hats: 1673(line=84, offs=1) --
1723(line=84, offs=51): error(1): the file
[{$PATSPRE}/DATS/array_quicksort.dats] is not available for
staloading.
patsopt(TRANS1): there are [4] errors in total.
exit(ATS): uncaught exception:
_2home_2brand_000_2ATS_2dPostiats_2src_2pats_error_2esats__FatalErrorExn(1025)




On Thu, Feb 5, 2015 at 7:24 AM, Kiwamu Okabe <notifications@github.com>
wrote:

> Following code occurs compile error.
>
> #include "share/atspre_staload.hats"
>
> fun f (x:int): int = 10 + x * (if x < 30 then 10 else 100)
>
> implement main0 () = println! (f 20)
>
> $ patscc no_duplicate_code.dats
> /home/kiwamu/doc/ATS_Foundations/source/code/conditional/no_duplicate_code.dats: 97(line=4, offs=27) -- 128(line=4, offs=58): error(3): the symbol [*] cannot be resolved due to too many matches:
> D2ITMcst(mul_int_double) of 0
> D2ITMcst(mul_int_float) of 0
> /home/kiwamu/doc/ATS_Foundations/source/code/conditional/no_duplicate_code.dats: 97(line=4, offs=27) -- 128(line=4, offs=58): error(3): the dynamic expression cannot be assigned the type [S2Eapp(S2Ecst(g1uint_int_t0ype); S2Ecst(size_kind), S2EVar(4143))].
> /home/kiwamu/doc/ATS_Foundations/source/code/conditional/no_duplicate_code.dats: 97(line=4, offs=27) -- 128(line=4, offs=58): error(3): mismatch of static terms (tyleq):
> The actual term is: S2Eerr()
> The needed term is: S2Eapp(S2Ecst(g1uint_int_t0ype); S2Ecst(size_kind), S2EVar(4143))
> /home/kiwamu/doc/ATS_Foundations/source/code/conditional/no_duplicate_code.dats: 92(line=4, offs=22) -- 128(line=4, offs=58): error(3): the dynamic expression cannot be assigned the type [S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind))].
> /home/kiwamu/doc/ATS_Foundations/source/code/conditional/no_duplicate_code.dats: 92(line=4, offs=22) -- 128(line=4, offs=58): error(3): mismatch of static terms (tyleq):
> The actual term is: S2Eapp(S2Ecst(g1uint_int_t0ype); S2Ecst(size_kind), S2Eapp(S2Ecst(add_int_int); S2EVar(4142->S2Eintinf(10)), S2EVar(4143)))
> The needed term is: S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind))
> patsopt(TRANS3): there are [3] errors in total.exit(ATS): uncaught exception: _2home_2kiwamu_2src_2ATS_2dPostiats_2src_2pats_error_2esats__FatalErrorExn(1025)
>
> Type-influencer can't know the type of conditional branch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/githwxi/ATS-Postiats/issues/128>.
>



-- 
Brandon Barker
brandon.barker@gmail.com

**Comment by githwxi** [comment]
Your share/atspre_staload.hats needs to be updated.

**Comment by githwxi** [comment]
Part of the reason is due to * being an overloaded symbol.
Two possible solutions:

```ats
//
fun f (x:int): int =
  10 + g0int_mul_int(x, if x < 30 then 10 else 100)
//
fun f (x:int): int = 10 + x * ((if x < 30 then 10 else 100):int)
//
```

**Comment by master-q** [comment]
Thank's, all.

However, why following also  have compile error?

```ocaml
#include "share/atspre_staload.hats"

fun f (x:int): int = 10 + x * (if x < 30 then 10:int else 100:int)

implement main0 () = println! (f 20)
```

```shell
$ patscc no_duplicate_code.dats
/home/kiwamu/tmp/no_duplicate_code.dats: 65(line=3, offs=27) -- 104(line=3, offs=66): error(3): the symbol [*] cannot be resolved due to too many matches:
D2ITMcst(mul_int_double) of 0
D2ITMcst(mul_int_float) of 0
/home/kiwamu/tmp/no_duplicate_code.dats: 65(line=3, offs=27) -- 104(line=3, offs=66): error(3): the dynamic expression cannot be assigned the type [S2Eapp(S2Ecst(g1uint_int_t0ype); S2Ecst(size_kind), S2EVar(4175))].
/home/kiwamu/tmp/no_duplicate_code.dats: 65(line=3, offs=27) -- 104(line=3, offs=66): error(3): mismatch of static terms (tyleq):
The actual term is: S2Eerr()
The needed term is: S2Eapp(S2Ecst(g1uint_int_t0ype); S2Ecst(size_kind), S2EVar(4175))
/home/kiwamu/tmp/no_duplicate_code.dats: 60(line=3, offs=22) -- 104(line=3, offs=66): error(3): the dynamic expression cannot be assigned the type [S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind))].
/home/kiwamu/tmp/no_duplicate_code.dats: 60(line=3, offs=22) -- 104(line=3, offs=66): error(3): mismatch of static terms (tyleq):
The actual term is: S2Eapp(S2Ecst(g1uint_int_t0ype); S2Ecst(size_kind), S2Eapp(S2Ecst(add_int_int); S2EVar(4174->S2Eintinf(10)), S2EVar(4175)))
The needed term is: S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind))
patsopt(TRANS3): there are [3] errors in total.
exit(ATS): uncaught exception: _2home_2kiwamu_2src_2ATS_2dPostiats_2src_2pats_error_2esats__FatalErrorExn(1025)
```

**Comment by bbarker** [comment]
That does look peculiar to me.

On Thu, Feb 5, 2015 at 11:24 PM, Kiwamu Okabe <notifications@github.com>
wrote:

> Thank's, all.
>
> However, why following also have compile error?
>
> #include "share/atspre_staload.hats"
>
> fun f (x:int): int = 10 + x * (if x < 30 then 10:int else 100:int)
>
> implement main0 () = println! (f 20)
>
> $ patscc no_duplicate_code.dats
> /home/kiwamu/tmp/no_duplicate_code.dats: 65(line=3, offs=27) -- 104(line=3, offs=66): error(3): the symbol [*] cannot be resolved due to too many matches:
> D2ITMcst(mul_int_double) of 0
> D2ITMcst(mul_int_float) of 0
> /home/kiwamu/tmp/no_duplicate_code.dats: 65(line=3, offs=27) -- 104(line=3, offs=66): error(3): the dynamic expression cannot be assigned the type [S2Eapp(S2Ecst(g1uint_int_t0ype); S2Ecst(size_kind), S2EVar(4175))].
> /home/kiwamu/tmp/no_duplicate_code.dats: 65(line=3, offs=27) -- 104(line=3, offs=66): error(3): mismatch of static terms (tyleq):
> The actual term is: S2Eerr()
> The needed term is: S2Eapp(S2Ecst(g1uint_int_t0ype); S2Ecst(size_kind), S2EVar(4175))
> /home/kiwamu/tmp/no_duplicate_code.dats: 60(line=3, offs=22) -- 104(line=3, offs=66): error(3): the dynamic expression cannot be assigned the type [S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind))].
> /home/kiwamu/tmp/no_duplicate_code.dats: 60(line=3, offs=22) -- 104(line=3, offs=66): error(3): mismatch of static terms (tyleq):
> The actual term is: S2Eapp(S2Ecst(g1uint_int_t0ype); S2Ecst(size_kind), S2Eapp(S2Ecst(add_int_int); S2EVar(4174->S2Eintinf(10)), S2EVar(4175)))
> The needed term is: S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind))
> patsopt(TRANS3): there are [3] errors in total.exit(ATS): uncaught exception: _2home_2kiwamu_2src_2ATS_2dPostiats_2src_2pats_error_2esats__FatalErrorExn(1025)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/githwxi/ATS-Postiats/issues/128#issuecomment-73181012>
> .
>



-- 
Brandon Barker
brandon.barker@gmail.com

**Comment by githwxi** [comment]
You can use  ` ` `ats ... ` ` ` now for ATS code :)

**Comment by master-q** [comment]
> You can use  ats ...  now for ATS code :)

What meaning?

**Comment by githwxi** [comment]
```text
```ats
...
```
```

**Comment by master-q** [comment]
Oh! Great github!

```ats
implement ats_serial_tx_vect () =
  if ringbuf_is_empty tx_buffer then {
    // Buffer empty, so disable interrupts
    val () = c_cbi (ADDR_UCSRB, BIT_UDRIE)
  } else {
    // There is more data in the output buffer. Send the next byte
    val c  = ringbuf_remove tx_buffer
    val () = $UN.ptr0_set<uchar> (ADDR_UDR, c)
  }
```

**Comment by master-q** [comment]
Umm... However, the code color between "{}" is not good...

**Comment by githwxi** [comment]
The type for (if ... then (10: int) else (100: int)) is X such that int <= X; the system does not assume
that X must be int. That is why you got the above type-error.

**Comment by githwxi** [comment]
You can report this issue here:

https://github.com/steinwaywhw/ats-mode-sublimetext/issues

**Comment by bbarker** [comment]
Ah yes, this reminds me of my first ATS question ever. :)

On Fri, Feb 6, 2015 at 12:03 AM, Hongwei Xi <notifications@github.com>
wrote:

> You can report this issue here:
>
> https://github.com/steinwaywhw/ats-mode-sublimetext/issues
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/githwxi/ATS-Postiats/issues/128#issuecomment-73183400>
> .
>



-- 
Brandon Barker
brandon.barker@gmail.com

**Comment by githwxi** [comment]
Type-checking in ATS involves analysis and synthesis.

Analysis: Checking whether an expression can be assigned a given type.
Synthesis: Computing the type of an expression based on the syntactic form of the expression

An if-then-else expression is considered an analysis-expression.

**Comment by bbarker** [comment]
I guess it makes sense to err on the side of being conservative, but it is
just a bit unusual and easy to forget.

On Fri, Feb 6, 2015 at 12:10 AM, Hongwei Xi <notifications@github.com>
wrote:

> Type-checking in ATS involves analysis and synthesis.
>
> Analysis: Checking whether an expression can be assigned a given type.
> Synthesis: Computing the type of an expression based on the syntactic form
> of the expression
>
> An if-then-else expression is considered an analysis-expression.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/githwxi/ATS-Postiats/issues/128#issuecomment-73183837>
> .
>



-- 
Brandon Barker
brandon.barker@gmail.com

**Comment by master-q** [comment]
Is the following URL for github highlighting? > @githwxi 

> https://github.com/steinwaywhw/ats-mode-sublimetext/issues

**Comment by master-q** [comment]
> When type-checking g0int_mul_int(10, if-then-else), the type-checker only needs to check whether if-then-else can be assigned the type int.

Ah----. I think I understand it.
However,,,,,, it's hard for me to explain it on my document...

http://jats-ug.metasepi.org/doc/ATS2/ATS_Foundations/conditional.html#conditional-branch-is-also-an-expression

**Comment by master-q** [comment]
I have more question. See following code:

```ats
#include "share/atspre_staload.hats"

fun f (x:int): int = ($showtype (if x < 30
                                 then $showtype 10
                                 else $showtype 100))

implement main0 () = println! (f 20)
```

Then compile it.

```shell
$ patscc no_duplicate_code.dats
**SHOWTYPE**(/home/kiwamu/tmp/no_duplicate_code.dats: 130(line=4, offs=49) -- 132(line=4, offs=51)): S2Eapp(S2Ecst(g1int_int_t0ype); S2Ecst(int_kind), S2Eintinf(10)): S2RTbas(S2RTBASimp(1; t@ype))
**SHOWTYPE**(/home/kiwamu/tmp/no_duplicate_code.dats: 181(line=5, offs=49) -- 184(line=5, offs=52)): S2Eapp(S2Ecst(g1int_int_t0ype); S2Ecst(int_kind), S2Eintinf(100)): S2RTbas(S2RTBASimp(1; t@ype))
**SHOWTYPE**(/home/kiwamu/tmp/no_duplicate_code.dats: 72(line=3, offs=34) -- 184(line=5, offs=52)): S2EVar(4172): S2RTbas(S2RTBASimp(1; t@ype))
```

Why conditional branch has type ``S2RTbas(S2RTBASimp(1; t@ype))``?

**Comment by githwxi** [comment]
``S2RTbas(S2RTBASimp(1; t@ype))`` is a sort (not a type). The type is ``S2EVar(4172)``.

In the current implementation, the type of the argument of $showtype is *always* synthesized.

**Comment by githwxi** [comment]
I have modified the implementation of $showtype: it now differentiates synthesis from analysis.

Try your above example in ATS2-0.1.9, and you will see the difference.

**Comment by master-q** [comment]
It's so good for human.

```
$ cat no_duplicate_code.dats
#include "share/atspre_staload.hats"

fun f (x:int): int = ($showtype (if x < 30
                                 then $showtype 10
                                 else $showtype 100))

implement main0 () = println! (f 20)
$ patscc no_duplicate_code.dats
**SHOWTYPE[DN]**(/home/kiwamu/tmp/no_duplicate_code.dats: 130(line=4, offs=49) -- 132(line=4, offs=51)): S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)): S2RTbas(S2RTBASimp(1; t@ype))
**SHOWTYPE[DN]**(/home/kiwamu/tmp/no_duplicate_code.dats: 181(line=5, offs=49) -- 184(line=5, offs=52)): S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)): S2RTbas(S2RTBASimp(1; t@ype))
**SHOWTYPE[DN]**(/home/kiwamu/tmp/no_duplicate_code.dats: 72(line=3, offs=34) -- 184(line=5, offs=52)): S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)): S2RTbas(S2RTBASimp(1; t@ype))
```

**Comment by master-q** [comment]
Umm.... Why can't also change if-then-else into one such like the new $showtype?

**Comment by githwxi** [comment]
Note that $showtype does not affect typechecking at all.

When you write

```ats
fun f (x:int):int = if ... then ... else ...
```

the code essentially translates into

```ats
fun f (x:int) = (if ... then ... else ...): int
```
