### ISSUE TITLE
Pattern match failure in pats_typerase_dynexp.dats

### ISSUE THREAD

**Issue by shlevy** [githwxi/ATS-Postiats#133]
With the following code:

```ats
fn foo (): void = let
  val buf_sz = i2sz(10)
  var buf = @[byte][buf_sz]()
in () end
```

I get:

> exit(ATS): /home/shlevy/src/ATS-Postiats/src/pats_typerase_dynexp.dats: 18567(line=820, offs=9) -- 18619(line=820, offs=61): match failure.

If I replace the second buf_sz with a literal 10 it all works.

**Comment by githwxi** [comment]
Thanks for reporting it.

This bug is now fixed. Changes have been uploaded.

**Comment by shlevy** [comment]
:beer:
