### ISSUE TITLE
Add inline/inl# function definition

### ISSUE THREAD

**Issue by shlevy** [githwxi/ATS-Postiats#137]
It would be nice to have `inline fn foo(): void` or `fn foo(): void = "inl#"` result in an `inline` C function being emitted. I tried to add this myself but I don't know the codebase well enough.

**Comment by bbarker** [comment]
[This post](https://groups.google.com/forum/#!searchin/ats-lang-users/inline/ats-lang-users/wiMvgMjzltI/nfEkcVLZJVcJ) has some related discussion

**Comment by githwxi** [comment]
A programmer would have a hard time knowing which functions should be inlined.
