### ISSUE TITLE
Segmentation fault in non-template functions

### ISSUE THREAD

**Issue by wdblair** [githwxi/ATS-Postiats#150]
Suppose you want to compute the length of a list that contains element of some flat type. Since the length of the list doesn't depend on the type of elements stored inside of it, you could write this as a non-templated function, like in the following sample code.

https://gist.github.com/wdblair/90444f1850b196409927

This file compiles fine with patscc, but when you run it, a segmentation fault occurs inside the length function.

https://gist.github.com/wdblair/2e0b7d1d56fcc395930d
See line 65 of the outputted C code.

I suspect the issue is that the length function cannot be implemented for all types because the list(a) datatype is compiled into a struct like the following
 
    struct {
         atstype_var data;
         void *next;
    } list_a;

Where atstype_var is a array of bytes of fixed size.

    typedef
    struct{char _[_ATSTYPE_VAR_SIZE];} atstype_var[0] ;

This breaks down when the list type gets instantiated on some type like `int` and is represented by the following C struct.

    struct {
        int data;
        void *next;
    } list_int;

Now, if I pass a pointer to list_int to the length function, I am certainly going to get a segmentation fault because it expects the *next pointer to be at a different offset in the struct. That is, the size of atstype_var and any other flat type are likely not going to be the same.

Of course, this behavior highlights one of the reasons I really like ATS; it's very flexible. The list datatype does not need to be a complicated boxed type like in other languages, it can literally just be a struct that holds data and a pointer to the next struct in the list.

My question is, "how could we have this create an error for the user, instead of causing a segmentation fault in the code?"

**Comment by wdblair** [comment]
I'm not sure if this helps, but one solution to this issue would be to compile all structs by first generating struct labels that are boxed, and then generating labels for unboxed values.

    struct {
        void *next;
        atstyvar_type(a) data;
    } list_a;

    struct {
        void *next;
        int data;
    } list_int;

but it seems like that may not work for more complicated types like a tree

    struct {
        void *left;
        void *right;
        atstyvar_type(a) data;
    } tree_data;

    struct {
        void *left;
        void *right;
        int data;
    } tree_int;

The issue I'm thinking is that these two structs are completely different from the perspective of the C compiler. Therefore, given a pointer to tree_int, can I be sure that

    offsetof(tree_a, right) == offsetof(tree_int, right)

**Comment by githwxi** [comment]
I feel that we need to write a tool to analyze the C code generated from ATS source. This tool will be able to generate information for the user that is otherwise difficult to do by patsopt directly.

**Comment by wdblair** [comment]
That would be a good idea, especially since you already have libatscc to parse the C code emitted by ATS.

I was thinking it could be worthwhile to generate llvm bit code from the C code. I remember there was some discussion about this on the mailing list, but it didn't seem that interesting because we could just use clang for the job.

What I like about compiling ATS to llvm bit code is that we can worry less about how the C compiler will interpret what we are doing. In this case, we would know that a set of structs are all specific implementations of one type and could avoid this issue. If the generated C code has information about which types are boxed and non-linear, we might be able use LLVM's garbage collection intrinsics to roll our own garbage collector

http://llvm.org/docs/GarbageCollection.html

**Comment by steinwaywhw** [comment]
I have the exact same problem. And I feel like moving pointers to the front of `struct` is a good idea.

**Comment by githwxi** [comment]
In ATS2, one is encouraged to use templates instead of polymorphic functions.

For a function like list_length, you really want to make sure that it is inlined. In general, short functions
should be written like

fun{} foo(...) = ...

**Comment by githwxi** [comment]
I managed a fix that can stop compilation if atstyvar_type is present.
In this way, the list_length code can no longer be compiled to object code via a C compiler.
The changes have been uploaded.
