### ISSUE TITLE
Using andalso leads to "pattern match is non-exhaustive" error

### ISSUE THREAD

**Issue by wdblair** [githwxi/ATS-Postiats#152]
Suppose I have the following program where I want to perform some action when a condition is true and a list is empty.

    extern
    fun
    check (): bool

    fun{a:t@ype}
    foo (xs: List0_vt(a)): void =
      if check() andalso length(xs) = 0 then let
        val ~list_vt_nil() = xs
      in
        ()
      end
      else
        list_vt_free(xs)

Inside the if statement, I assume the list is empty, since it has a length of 0. This creates a type checking error. If I omit the "andalso" and just have the if statement check for an empty list, type checking passes.

Of course, I could just call list_vt_free instead of doing pattern matching, but I was curious pattern matching could be supported in this case.

**Comment by githwxi** [comment]
This is due to 'andalso' being given a very imprecise type.

You could use (check() * length(xs)), where * is multiplication on booleans

(You need to update your ATS as I just fixed some issues with *)
