### ISSUE TITLE
Negating predicates on reals

### ISSUE THREAD

**Issue by paul7** [githwxi/ATS-Postiats#161]
The constraint solver doesn't seem to be aware of relations between constraints on reals.
E.g. it doesn't know that (a == b) is equivalent to ~(a != b). This is not the case with integer constraints, of course.
I observe this behaviour on the today's git version of Potsiats.

Consider the following signature:
```
extern
fun iszero_real
{a: real}
(a: real(a)):
bool(a != i2r(0))
```

The following implementation fails to compile due to unsolved constraint:
```
implement iszero_real{a}(a) =
  if eq_real_int(a, 0)
  then 
    false
  else
    true
```

But this one is fine:
```
implement iszero_real{a}(a) =
  if ~neq_real_int(a, 0)
  then 
    false
  else
    true
```

**Comment by githwxi** [comment]
I suppose that you used the built-in solver for ATS.

Note that the built-in solver in ATS cannot really handle constraints on reals.

I suggest that you try the above example using z3.

patsopt --constraint-export -tc -d <your-example.dats> | patsolve_z3 -i
