### ISSUE TITLE
Add tags for each release

### ISSUE THREAD

**Issue by steinwaywhw** [githwxi/ATS-Postiats#163]
Hi,

Is it ok for you to add tags for every new release? Tags will help docker easily find a specific version to build.

**Comment by githwxi** [comment]
How should I do it?

Currently, there is a file VERSION in each released package that contains the version info.

**Comment by steinwaywhw** [comment]
You can do the followings:

```bash
git commit ... # as usual
git tag -a 0.2.9
git push --tags ... # as usual, but with --tags option
```

Then in the installation script of Dockerfile, we can refer to this tag. Currently I'm checking out a specific commit.

**Comment by githwxi** [comment]
Okay, I just added a tag v0.2.11 and pushed it.

**Comment by steinwaywhw** [comment]
Thanks! b.t.w. the contrib repo also need tags.

**Comment by githwxi** [comment]
ATS2-contrib is now tagged with v0.2.11 as well.

**Comment by jonathonf** [comment]
Is the 0.2.11 tag the actual final 0.2.11 release? If not, please tag it as a pre-release (e.g. 0.2.11pre).

**Comment by githwxi** [comment]
I changed the tag to v0.2.11-pre.

**Comment by githwxi** [comment]
I have just added the tag v0.2.11 to indicate ATS2-0.2.11 is ready for release.
