### ISSUE TITLE
All versions should be tagged, not just the pre-release

### ISSUE THREAD

**Issue by jonathonf** [githwxi/ATS-Postiats#164]
Currently the repo has a single available tag, 0.2.11.

As a feature request, please tag all releases with their version number, and pre-releases as, e.g. 0.2.11pre

This allows much easier comparisons between releases, e.g. for locating regressions.

**Comment by jonathonf** [comment]
Duplicate of: https://github.com/githwxi/ATS-Postiats/issues/163

**Comment by githwxi** [comment]
We have just started using tags. The future release will all be tagged.
