### ISSUE TITLE
ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [githwxi/ATS-Postiats#166]
I am wondering if there is a possibility to switch the license to ASL 2.0?

**Comment by master-q** [comment]
I think the person choosing GPLv3 has strong policy for the license.
Why do you believe ASL 2.0 license is better than GPLv3 for the future of ATS compiler?

**Comment by sirinath** [comment]
GPL is viral. Also ASL 2.0 be deemed more business friendly and generally whitelisted by many organisations. Moving to ASL 2.0 means more will start using ATS also if they are not using it due to the license.

**Comment by cosmo0920** [comment]
:-1:
I think that GPL is NOT viral. People choosing GPLv3 strongly want to know derivative works.
If we choose not copy-left and bussiness kindly license, original authors cannot know all of derivative works.

**Comment by sirinath** [comment]
Many companies might not want to use ATS because it is GPL.

**Comment by cosmo0920** [comment]
GPLv3 does not request always to be open sourced derivative works if they are used in Cloud or Web services and users do not have its binaries consist of GPLv3.

**Comment by sirinath** [comment]
You have no control over the licensing when you distribute.

**Comment by cosmo0920** [comment]
Yes, GPLv3 does not have distributing control, but it ensure to remain to be open source even if its derivative works.

**Comment by sirinath** [comment]
The question is do you want more adaptation of ATS business users who might be concerned with the limitation of GPL imposed on them or not. Moving away from GPL means companies who might have not been able to use ATS because if is GPL can start using it. Also if their dependence ATS becomes higher they might contribute back also than the forced contribution of the GPL model to which many companies do not use hence do not end up contributing.

**Comment by cosmo0920** [comment]
If a source codes are licensed GPL, business users can use their businesses.
There is plenty of way to business which uses GPL licensed software.
If you just hate only GPL and strongly insist of changing license from GPL to other having a high affinity for proprietary software, it is too selfish thinking for GPL licensed open source software.
Please respect developers who use and love GPL license for their software products.

**Comment by sirinath** [comment]
I am just asking. It is upto the copyright holder to make the licensing decision. It is not hating or loving a license from our perspective but what makes more business sense to use.

**Comment by githwxi** [comment]
First, thanks for everyone's interest!

Yes, GPL is indeed "viral" (in my opinion), but being "viral" is really the point of GPL. However, I would like to stick to GPL for the moment. Here is my reasoning:

First kind of application:
If you use ATS to write code for your company (e.g., implementing drivers or building web pages), then there is nothing of concern in term of copyright. You own 100% copyright of your code and you can do whatever you want with your own code.

Second kind of application:
If you try to extend ATS with features, then I would like that you make these features available to other people for free.

GPL may hinder a business doing the second kind of application, but I feel it is a reasonable price to pay.

**Comment by sirinath** [comment]
Also getting client approvals addressing legal concerns to use a GPL software is an additional overhead for small outsourcing / contracting companies. Also it is more difficult to sell and market solutions which use GPL / copyleft licenses in dependencies. The reasonable price based on the size of the organisation. There are many more smaller organisations than larger ones.

Though the main argument is always giving back modification, the number of cases a piece of software is forked or modified is less compared to those who just use it but nevertheless have to pay the price if you use copyleft because of the extra overheads.

**Comment by githwxi** [comment]
What you said (the first paragraph) is very true. I completely understand as I myself have my own stories to back it up. In the past, I did see licenses targeting "small" companies (say, with a revenue less than $1M).

As for the second paragraph, I see it as a price to pay for living in today's society. For a programming language, I would say GPL is quite reasonable. For a web server, I would probably go for ASL because the need to embed a programming language is far less than the need to embed a web server.
