### ISSUE TITLE
Runtime Pattern Matching Failure in `atscc2js`

### ISSUE THREAD

**Issue by steinwaywhw** [githwxi/ATS-Postiats#168]
<https://github.com/githwxi/ATS-Postiats/blob/master/contrib/CATS-atscc2js/DATS/atscc2js_emit2.dats#L365>

When writing pattern matching expressions in the following style, it will cause runtime failure in `atscc2js`

```
datatype one_t = OnlyOneConstructor of ()

case+ some_option_value_of_one_t of
| None () => ...
| Some(OnlyOneConstructor()) => ...
```

The last line above passed type-checking, but it will cause `atscc2js` to fail in the `ATSifthen` case.

**Comment by githwxi** [comment]
Yes, I experienced this as well. For the moment, please try:

case+ ... of
| None () => ...
| Some x => let val OnlyOneConstruct() = x in ... end

**Comment by githwxi** [comment]
I think that this one is fixed. I have uploaded the changes.
