### ISSUE TITLE
Errors in the introduction tutorial

### ISSUE THREAD

**Issue by antoyo** [githwxi/ATS-Postiats#172]
In the chapter 3 (on functions), the following code does not compile:
```ats
fun
ifold2
(
  n: int, f: (int, int) -<cloref1> int, ini: int
) : int =
  if n > 0 then f (ifold2 (n-1, f, ini), n) else ini
// end of [ifold2]
//
fun
sqrmodsum (n: int, d: int): int =
  ifold2 (n, lam (res, x) => if x mod d then res + x * x else res, 0)
```
A `= 0` is missing after `x mod d` on the last line.
This is in the Higher-Order Functions chapter.

Also, in the next chapter, Example: Binary Search, the following code doesn't work:
```ats
val
ISQRT_MAX = (1 << 16) - 1 // = 65535
//
fun isqrt
  (x: uint): int =
  bsearch_fun (lam i => square(g0i2u(i)), x, 0, ISQRT_MAX)
```
I don't know how to fix it though (sorry, I just started to learn the language).

Thanks to fix these issues.

**Comment by githwxi** [comment]
Thanks!

I fixed the first issue (missing '= 0').

I don't know what is wrong with the second one. I tried the code
and it did work for me. The running bsearch code can be found here:

https://github.com/ats-lang/ats-lang.github.io/blob/master/DOCUMENT/INT2PROGINATS/CODE/CHAP_FUNCTION/bsearch.dats

**Comment by antoyo** [comment]
Ah, the macro was missing:
```
macdef
square (x) = let val x = ,(x) in x * x end
```
Perhaps it should be added in the chapter or you could tell this macro is defined somewhere.
Thanks.

**Comment by githwxi** [comment]
Done.

**Comment by antoyo** [comment]
Thanks.
