### ISSUE TITLE
Code for matrices doesn't compile

### ISSUE THREAD

**Issue by antoyo** [githwxi/ATS-Postiats#173]
Hello.
The code from the chapter about matrices is different than the one in the github repo, thus it does not compile.
There are missing calls to `i2sz` and `succ` needs to be used instead of `+ 1`.

Why can't we use ` + 1` for `size_t`?

Thanks to fix this.

**Comment by githwxi** [comment]
Thanks!

I fixed both issues (i2sz and succ).
You can now do x + 1 (or x + any-natural-number) even when x is a size_t.

The fixes will be officially available in the next release (ATS2-0.3.7).

The Intro-to-ATS book was partly written before ATS2 coming out. So some code
in it is still of the style of ATS1.

I am working on a set of lecture notes that primarily focus on functional programming (FP):

http://ats-lang.sourceforge.net/DOCUMENT/ATS2FPCRASH/HTML/HTMLTOC/book1.html

If you are interested in FP, please take a look at the lecture notes once you have finished Part I and Part II
in the Intro-to-ATS books.

Cheers!

**Comment by antoyo** [comment]
Yes, I am interested in functional programming: I used OCaml and Haskell before.
Nowadays, I'm a lot into Rust.
I'll look at this crash course, thanks.

**Comment by githwxi** [comment]
FP in ATS is more like in OCaml. Two big differences lie in (1) embeddable templates and (2) linear lazy-streams. When used as systems programming language, ATS is a bit like wrapping C+templates with a type system.
