### ISSUE TITLE
 *** No rule to make target 'patsopt'.  Stop. when building on Cygwin

### ISSUE THREAD

**Issue by cr1901** [githwxi/ATS-Postiats#177]
When attempting to compile ATS-Postiats on Cygwin (64-bit), I run into the following issues trying to build ATS:

* First off, `install-sh` is missing. I'm not sure why `install-sh` is even required in the first place, since this code base doesn't use `automake`. But that's `autotools` for you. I fixed this by running `automake --add-missing` on a clean/checked out repository, and then run `./autogen.sh` and `./configure`.

* When I run make after the above steps, the following error occurs:

```
William@William-THINK ~/src/ATS-clean
$ make
\
make -j4 -C src/CBOOT patsopt \
CCOMP=gcc GCFLAG= LDFLAGS=
make[1]: Entering directory '/home/William/src/ATS-clean/src/CBOOT'
make[1]: *** No rule to make target 'patsopt'.  Stop.
make[1]: Leaving directory '/home/William/src/ATS-clean/src/CBOOT'
make: *** [Makefile:72: src2_patsopt] Error 2

William@William-THINK ~/src/ATS-clean
$
```

I am uncertain how to debug this nor do I know how should the Makefiles be fixed. I've noticed the Cygwin build has been broken due to unrelated changes, so perhaps the Makefile wasn't updated properly recently? I'll take a look if I have time.

System information:

```
William@William-THINK ~/src/ATS-clean
$ uname -a
CYGWIN_NT-6.1 William-THINK 2.9.0(0.318/5/3) 2017-09-12 10:18 x86_64 Cygwin
```

**Comment by githwxi** [comment]
Could you show the content of the Makefile in src/CBOOT?
There should be a target of the name 'patsopt' in it.

**Comment by cr1901** [comment]
>Could you show the content of the Makefile in src/CBOOT?
>There should be a target of the name 'patsopt' in it.

So funny thing about your request; there is _no_ `Makefile` in `src/CBOOT`. So this explains why the build bombs.

```
William@William-THINK ~/src/ATS-clean
$ ls src/CBOOT/
ccomp  config.h  JS  libats  libc  prelude  README

William@William-THINK ~/src/ATS-clean
```

`./configure` did succeed though, so I'm not sure what's happening.

**Comment by githwxi** [comment]
I like the mystery :)

How did you get the ATS package?

**Comment by cr1901** [comment]
>How did you get the ATS package?

According to `less ~/.bash_history`, I did `git clone https://github.com/ats-lang/ATS-Postiats-release.git`

While I was attempting to fix the install-sh problem, I also did (in the same directory) `git clone ATS-Postiats-release/ ATS-clean`.

_Both_ versions are identical at this point, and both are missing `src/CBOOT/Makefile`, I've just been doing all my work in `ATS-clean`.

My issue w/ debugging at this point is that I'm not familiar w/ how you set up the Makefiles since you're using only `autoconf` and not `automake`. Which is fine- I can debug `autoconf`, but I would like a high-level overview of the Makefile structure to know where to look for errors efficiently.

**Comment by githwxi** [comment]
I think the mystery is now solved.

Please use the following git-repo instread:

https://sourceforge.net/p/ats2-lang/code/ci/master/tree/

ATS-Postiats-release is for preparing the above release (and some docker images).

**Comment by cr1901** [comment]
Closing issue, Cygwin compile works fine w/ your suggestion.

The intent of me doing a Cygwin compile was to compare to a native Windows compile (mingw-w64) and gauge how much work it would be to actually run on Windows (mostly `fcntl.h` issues). But that's a separate PR/Issue :).
