### ISSUE TITLE
intinf example fails to load due to bad include

### ISSUE THREAD

**Issue by techate** [githwxi/ATS-Postiats#178]
The attached code, mostly using the example from 'Introduction to Programming in ATS', fails with this error:

`patscc -O2 -flto -D_GNU_SOURCE -DATS_MEMALLOC_LIBC fact2.dats -o fact2 -latslib -lgmp
fact2_dats.c:1248:1: fatal error: atscntrb-libgmp/CATS/gmp.cats: No such file or directory
 "atscntrb-libgmp/CATS/gmp.cats"
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.`

This is due to the `#include` at the top of ats2-postiats-0.3.9/contrib/atscntrb-libgmp/SATS/gmp.sats

The attached builds and works fine when that file is edited to instead include include "contrib/atscntrb-libgmp/CATS/gmp.cats", with the leading "contrib/"

[fact2.txt](https://github.com/githwxi/ATS-Postiats/files/1610970/fact2.txt)

**Comment by githwxi** [comment]
Or you can use the following command-line to compile the code:

```shell
patscc -I${PATSHOME}/contrib -O2 -flto -D_GNU_SOURCE -DATS_MEMALLOC_LIBC fact2.dats -o fact2 -latslib -lgmp
```

**Comment by githwxi** [comment]
By the way, I suggest using mylibies.hats:

```
#define
HX_INTINF_targetloc
"contrib/atscntrb-hx-intinf"

#include "{$HX_INTINF}/mylibies.hats"

typedef intinf = $GINTINF_t.intinf
overload print with $GINTINF_t.print_intinf
```

Internal files in DATS may change. The file mylibies.hats serves as an interface for this package.
