### ISSUE TITLE
`PMVtmpltcstmat' undeclared with 5-tuple hashtblref value

### ISSUE THREAD

**Issue by techate** [githwxi/ATS-Postiats#180]
This compiles just fine:

    #include "share/atspre_staload.hats"
    #include "share/atspre_staload_libats_ML.hats"
    
    local typedef key = string and itm = (int, int, int, int) in
      #include "libats/ML/HATS/myhashtblref.hats"
    end
    
    implement main0() = ()

The same code with five ints, however...

    #include "share/atspre_staload.hats"
    #include "share/atspre_staload_libats_ML.hats"
    
    local typedef key = string and itm = (int, int, int, int, int) in
      #include "libats/ML/HATS/myhashtblref.hats"
    end
    
    implement main0() = ()

...fails to compile with these errors:

    $ make hashtest4
    patscc -O2 -flto -D_GNU_SOURCE -DATS_MEMALLOC_LIBC hashtest4.dats -o hashtest4 -latslib
    In file included from hashtest4_dats.c:15:0:
    hashtest4_dats.c: In function ‘ATSLIB_056_prelude__fprint_val__363__1’:
    hashtest4_dats.c:24641:23: error: ‘PMVtmpltcstmat’ undeclared (first use in this function)
     ATSINSmove(tmp818__1, PMVtmpltcstmat[0](tostrptr_val<S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int), 2=S2Ecst(int), 3=S2Ecst(int), 4=S2Ecst(int))>)(arg1)) ;
                           ^
    /usr/local/lib/ats2-postiats-0.3.9/ccomp/runtime/pats_ccomp_instrset.h:276:37: note: in definition of macro ‘ATSINSmove’
     #define ATSINSmove(tmp, val) (tmp = val)
                                         ^~~
    hashtest4_dats.c:24641:23: note: each undeclared identifier is reported only once for each function it appears in
     ATSINSmove(tmp818__1, PMVtmpltcstmat[0](tostrptr_val<S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int), 2=S2Ecst(int), 3=S2Ecst(int), 4=S2Ecst(int))>)(arg1)) ;
                           ^
    /usr/local/lib/ats2-postiats-0.3.9/ccomp/runtime/pats_ccomp_instrset.h:276:37: note: in definition of macro ‘ATSINSmove’
     #define ATSINSmove(tmp, val) (tmp = val)
...
[hashtest4.log](https://github.com/githwxi/ATS-Postiats/files/1694380/hashtest4.log)

I noticed this first with a record type of seven elements (1x bool and 6x float). These errors seems to obtain with any tuple of more than four elements of any type, and when any kind of array type is used for the value, or when `string(int)` is provided, etc.

**Comment by githwxi** [comment]
At this point, fprint is only defined for tuples containing 4 or fewer elements:

http://ats-lang.sourceforge.net/DOCUMENT/ATS-Postiats/prelude/DATS/CODEGEN/tuple.atxt

I could add a few more. Right now, you need to implement 'fprint_val' for the type itm.
A dummy version is given below:

```ats
implement fprint_val<itm>(out, x) = ()
```

**Comment by techate** [comment]
OK, cool. Since the original use case was a specific record type, more fprint_tupval# functions in tuple.dats wouldn't've helped anyway. After implementing the right `fprint_val` I now have a warning that doesn't seem to cause any problems, at least so far. The rest of the code is working fine.

    $ make hashtest4
    patscc -O2 -flto -D_GNU_SOURCE -DATS_MEMALLOC_LIBC hashtest4.dats -o hashtest4 -latslib
    In file included from hashtest4_dats.c:15:0:
    hashtest4_dats.c: In function ‘ATSLIB_056_libats_056_hashtbl_chain__hashtbl_foreach__fwork__332__1’:
    hashtest4_dats.c:24494:31: warning: implicit declaration of function ‘fprint_point_3’; did you mean ‘fprint_point_0’? [-Wimplicit-function-declaration]
     ATSINSmove_void(tmpret760__1, fprint_point_3(env0, ATSderef(arg1, postiats_tyrec_0))) ;
                                   ^
    /usr/local/lib/ats2-postiats-0.3.9/ccomp/runtime/pats_ccomp_instrset.h:284:39: note: in definition of macro ‘ATSINSmove_void’
     #define ATSINSmove_void(tmp, command) command
                                           ^~~~~~~

I'll go ahead and close this issue.

If it's going to be a while before patscc can provide errors like "you forgot to implement fprint_val<itm>", maybe functor-like modules can produce their own errors? Similar to `#ifndef FOO` -> `#error FOO NOT DEFINED` in C headers.

**Comment by githwxi** [comment]
Reporting informative template instantiation errors is very challenging issue.
It is a big reason that motivates me to go for ATS3 :). Though, not so sure yet.

The warning message you received is harmless in this case, but it is still a bit of disturbance.
It is strange to me as to why 'fprint_point_3' is not declared. If you show me your source code,
I may be able to explain.

**Comment by techate** [comment]
The following code compiles with that same warning (for fprint_earthquake_3):

    #include "share/atspre_staload.hats"
    #include "share/atspre_staload_libats_ML.hats"
    
    typedef earthquake = @{
      name = string,
      richter = float,
      depth = float, (* kilometers *)
      latitude = float,
      longitude = float
    }
    
    fn fprint_earthquake(out: FILEref, x: earthquake): void = (
      fprint_string(out, "@{");
      fprint_val<string>(out, x.name);
      fprint_string(out, ", ");
      fprint_val<float>(out, x.richter);
      fprint_string(out, ", ");
      fprint_val<float>(out, x.depth);
      fprint_string(out, ", ");
      fprint_val<float>(out, x.latitude);
      fprint_string(out, ", ");
      fprint_val<float>(out, x.longitude);
      fprint_string(out, "}");
    )
    
    implement fprint_val<earthquake> = fprint_earthquake
    fn print_earthquake(x: earthquake) = fprint_earthquake(stdout_ref, x)
    overload print with print_earthquake
    
    local typedef key = string and itm = earthquake in
      #include "libats/ML/HATS/myhashtblref.hats"
    end
    
    implement main0() =
      let
        val quakes = myhashtbl_make_nil(100)
        val-~None_vt() = quakes.insert("813270953", @{ name = "Colima, Meixco",
                                                     richter = 8.0f,
                                                     depth = 33.0f,
                                                     latitude = 19.055f,
                                                     longitude = ~104.205f })
        val-~None_vt() = quakes.insert("126335479", @{ name = "Haiti region",
                                               richter = 7.0f,
                                               depth = 13.0f,
                                               latitude = 18.443f,
                                               longitude = ~72.571f })
        fn check(c: string): void =
          case+ quakes.search(c) of
          | ~None_vt() => println!("unknown earthquake: ", c)
          | ~Some_vt(x) => println!("found earthquake: ", c, ": ", x)
      in
        check("813270953");
        check("1517862437");
        check("1263354790");
      end

**Comment by githwxi** [comment]
It turns out that a function called in a template is required to be external (global):

```ats
extern
fun fprint_earthquake : fprint_type(earthquake)
implement fprint_earthquake(out, x) = ...
```
