### ISSUE TITLE
Simplify Licensing of ATS2

### ISSUE THREAD

**Issue by sidkshatriya** [githwxi/ATS-Postiats#190]
I'm new to ATS. The possibility of doing reliable systems programming in ATS is very exciting.

First, thank you for releasing ATS to the world. You had no obligation to release it with an open source license but you have and I greatly appreciate it.

Looking at your repo I see the the following licensing language:

> The Compiler (ATS/Postiats): GPLv3
The source for Libraries (ATSLIB/{prelude,libc,libats}): GPLv3.
The object code for Libraries (ATSLIB/{prelude,libc,libats}): LGPLv2.1.
As a special exception, if you link the object code for Libraries with other files to create an executable, then the linking does not by itself cause the executable to be covered by LGPLv2.1. However, this exception does not invalidate any other reasons that might result in the executable being covered by LGPLv2.1.
The contributed portion (ATS/Postiats/contrib) is released under the MIT license.
There is also a release under the MIT license for the C header files of the Libraries, which one can freely insert into any C code generated from ATS source code.

To me this seems complex and a bit confusing. For people wanting to adopt ATS, they would need to do a good amount of research to see if these licensing terms would be OK for their use case. Due to the viral / copyleft nature of GPL it becomes especially important to do this research.

It is reassuring that the library is LGPL but then I'm confused about the fact that only the library object code is LGPL2.1  but the library source code is GPLv3. To me, at least, this is novel -- usually the source code and its transformation to object code would carry the same license. Here you are making a distinction. Is it possible to make such a distinction? The compilation of a GPLv3 file to object code should (normally) result in object code that is GPLv3 isn't it? Here you seem to be giving an interesting freedom/exception -- something that I've not encountered elsewhere.  Maybe I misunderstood?

Then the compiler itself is GPLv3. Like gcc (which itself is GPLv3) the output of the compiler itself should be not be encumbered by any additional license/copyrights held by ATS author -- at least that is my understanding. Of course the libraries continue to remain LGPL 2.1

> There is also a release under the MIT license for the C header files of the Libraries, which one can freely insert into any C code generated from ATS source code.

Thank you for this additional freedom. However I feel that this additional freedom is symptomatic of the underlying complexity of the ATS licensing, perhaps.

May I suggest that the ATS2 licensing be simplified? Is it possible to release all of ATS under a more liberal license like Apache 2.0/BSD/MIT etc.? Now there is a valid use case for the use of GPL and it depends on your personal preferences. However, if one of your aims is for greater adoption and a development of a community of companies and interested individuals to coalesce around the project -- a more permissive license might come handy. Please consider that! 

Once again, I respect your use of GPL/LGPL and you are under no obligation to give more liberal licensing if it does not align with your preferences.

If it is not possible to release ATS under a more liberal license, can you please simplify the licensing situation to make things a bit more permissive (while still remaining "copyleft")? Also can you clarify what you mean by library source being under one license and the compiled library object being under another license?

**Comment by cosmo0920** [comment]
Dis you read https://github.com/githwxi/ATS-Postiats/issues/166 and https://github.com/githwxi/ATS-Postiats/issues/154?

**Comment by sidkshatriya** [comment]
@cosmo0920 I did now. Thanks for pointing to them. However, there are some new questions/concerns pointed out above. Look forward to any possible reply from @githwxi !

**Comment by githwxi** [comment]
GPL was primarily for code written in C.

ATS system = ATS compiler + ATS libraries

What I really wanted to say is that any C code generated by the ATS compiler with the ATS libraries is
NOT considered, by default, to be licensed under GPLv3.

Can the source of a library and the object code compiled from the source be given difference GPL/LGPL
licenses? I have not seen it done elsewhere, but why not?

If one produces a product that contains part of the source code in the ATS system, then the product is obligated to be licensed under GPL. If no such source code is included, then there is no such an obligation.
C code generated from ATS code is not regarded as source code.

**Comment by sidkshatriya** [comment]
@githwxi Thank you for your response.

Why not keep everything simple and license your library object & source code *both* under LGPL (In fact please don't make a distinction between compiled/source form of the library)? If anybody starts changing/building upon the library source code (and distributing that code) they need to release the source code if if were under the LGPL as far as I understand it. Of course the "special exception" for linking with the library is another important thing that you have mentioned -- thank you for that freedom.

Regarding source/object license being different. Its a valid point -- just because one may not seen it done elsewhere, it does not mean you cannot do it. But it strikes me as weird -- transformation of source code (which is what compilation is) should not magically result in the license changing from GPLv3 to LGPL 2.1.

Why not put the library generally under LGPL? What is GPLv3 giving you for library source that LGPL isn't?

Disclaimer: I am not a lawyer so please don't rely on anything I've said in this ticket as definitive. My understandings of the various licenses may be wrong/flawed. Please read the seek formal advice in case you're not sure or maintain status quo as you feel comfortable.

**Comment by LoPoHa** [comment]
Hi @githwxi 

DISCLAIMER: I'm neither really experienced with licensing nor with ATS (Im currently 30% through [this Book](http://ats-lang.sourceforge.net/DOCUMENT/INT2PROGINATS/HTML/book1.html). Is this the best way to learn ATS?)

If I get you and the MPL2 (Mozilla Public License) right you should take a look at it.
It's not viral like the GPL and allows e.g. static linking. But you have to give back any modifications.
(Talking about the Standard Lib, not the Compiler itself)

And could you explain what happens if I compile ATS to e.g. JS? AFAIK You talk about the C Code not to be under GPL, but what about other compiler targets?

**Comment by githwxi** [comment]
If you compile ATS code to JS, you need to first compile it to C. As the generated C code is not under GPL, it is an automatic conclusion that anything generated from it is not under GPL, either.

MPL2 is a possibility. I will take a closer look at some stage. Right now., really busy with ATS3 :)

As for learning ATS, the following book may also be of some interest:

http://ats-lang.sourceforge.net/DOCUMENT/ATS2FUNCRASH/HTML/book1.html

The way in which linear streams are used to handle input and output should be new to people who have never done programming with linear types. I think it is an eye opener.

**Comment by LoPoHa** [comment]
Ah, ok.
I thought it would be ATS -> JS and not ATS -> C -> JS.
This makes sense now :)

I'll have a look at that Book when I'm home. Thanks!
