### ISSUE TITLE
Cannot parse let binding in #define macro

### ISSUE THREAD

**Issue by rightfold** [githwxi/ATS-Postiats#195]
It seems like the compiler cannot parse the following code in a dats file:

```ats
#define my_macro(a)
    let
        val a_once = a
    in
        a_once + a_once
    end
```

It fails with the following errors:

<pre>
/tmp/956953528/main.dats: 25(line=2, offs=5) -- 28(line=2, offs=8): error(parsing): the token is discarded.
/tmp/956953528/main.dats: 56(line=4, offs=5) -- 58(line=4, offs=7): error(parsing): the token is discarded.
exit(ATS): uncaught exception: _2tmp_2ATS2_2src_2pats_error_2esats__FatalErrorExn(1025)
</pre>

Is this intentional or is this a bug?

**Comment by githwxi** [comment]
For this, you need to use macdef:

#include
"share/atspre_staload.hats"

macdef my_macro(a) =
 let
    val a_once = ,(a)
 in
    a_once + a_once
 end

fun double(x: int): int = my_macro(x)

implement main0() = ()

val () = println!("double(10) = ", double(10))

**Comment by rightfold** [comment]
Thank you, that seems to work.

It seems that with macdef and macrodef, you cannot use variables that aren’t in scope when defining the macro. But with #define macros, you can. For example:

```ats
#define foo(a) a + b

implement main0() =
    let val b = 1 in
        print foo(2) end
```

So if you want this and you also want a let binding, it seems impossible?

**Comment by githwxi** [comment]
'#define' is basically string replacement.

Currently, only simple expressions are supported for being using with '#define'.

**Comment by jrfondren** [comment]
You can combine #define with macdef though:

    #include "share/atspre_staload.hats"

    macdef plus(a, b) =
            let
                    val v = ,(a)
            in
                    v + ,(b)
            end

    #define plusb(a) plus(a, b)

    implement main0() =
            let
                    val b = 1
                    val x = plusb(41)
            in
                    println!("x: ", x);
            end
