### ISSUE TITLE
`T_CDATA`: is it used?

### ISSUE THREAD

**Issue by Hibou57** [githwxi/ATS-Postiats#197]
`pats_lexing.sats` introduce the token type `T_CDATA` which seems to never be instantiated. The only reference to it I can find, is in a case statement in `pats_lexing_print.dats`. Since it seems to never be instantiated, I guess this branch can never be reached and this token could simply be removed. Is it? (providing I’m not missing something)

**Comment by githwxi** [comment]
Right now, T_CDATA is not used.

It was introduced for inputting binary data. It may still be a possibility in future, though.

**Comment by Hibou57** [comment]
I guess it’s the same with `T_SRPCODEGEN3`. It’s a lexical unit not referred to by parsing.

**Comment by githwxi** [comment]
This one is not in use. It was introduced for supporting some kind of meta-pragramming.
