### ISSUE TITLE
“[mpz_init_set_str()] failed” while lexing

### ISSUE THREAD

**Issue by Hibou57** [githwxi/ATS-Postiats#201]
Type‑checking this (for a test):

        val a = 0xu

Which after `pats_lexing.dats`, should be the same as 0x0u, I get this error message from `patsopt`:

> exit(ATS): [mpz_init_set_str()] failed

Unfortunately, it gives no source location. Pretty sure the error occurs while lexing.

**Comment by Hibou57** [comment]
It’s in GMP, so no, it’s later after lexing is done, because lexing only stores the `T_INT` string, does not evaluate it.

**Comment by githwxi** [comment]
mpz_init_set_str treats empty string "" as invalid input.
I have fixed this issue.

**Comment by githwxi** [comment]
By the way, if you pass the flag '--debug' to patsopt, the compiler
can give you a bit of information when an error occurs.

**Comment by Hibou57** [comment]
You are really nice :)

I did not knew the `--debug` flag, will keep it in mind. It indeed gives relevant informations.
