### ISSUE TITLE
Multiple patterns

### ISSUE THREAD

**Issue by antoyo** [githwxi/ATS-Postiats#208]
Hi.
Is it possible to have multiple patterns with the same body like:
```ats
case 10 of | 1 | 2 => println!("one or two")
```
?
By the way, I wonder if there is a syntax reference somewhere that consicely shows all the syntax of the language and what it does.
Thanks for your help.

**Comment by antoyo** [comment]
Thanks for posting the grammar.
However, I was looking for something a bit more descriptive, because it does not explain how a particular bit of grammar works.
Do you have such a reference?
Thanks.

**Comment by githwxi** [comment]
Sorry, I don't have it. Hope that someone will write one some day :)

**Comment by githwxi** [comment]
A liveness property: What liveness property do you refer to?

**Comment by githwxi** [comment]
By the way, disjunctive patterns (i.e., multiple patterns) are to be supported in ATS3. I have already
added syntactic support.
