### ISSUE TITLE
Comparing generic types

### ISSUE THREAD

**Issue by antoyo** [githwxi/ATS-Postiats#210]
Hi.
I wrote the following function to check if a generic list is a palindrome:
```ats
fun {a: t@ype} isPalindrome(xs: list0(a)): bool =
    list0_equal<a>(xs, list0_reverse<a> xs, lam (a, b) => a = b)
```
But it does not compile, because `=` cannot be resolved.
How can I make this works?
Is there some concept of typeclasses in ATS?
Thanks.

**Comment by githwxi** [comment]
Try:

lam(a, b) => geq_val_val<a>(a, b)

By the way, you could use stackoverflow:

https://stackoverflow.com/questions/tagged/ats

Usually, questions on ATS are answered more promptly there.

**Comment by antoyo** [comment]
Thanks.
I'll post on StackOverflow from now on.
