### ISSUE TITLE
Add function in ML to set the seed

### ISSUE THREAD

**Issue by antoyo** [githwxi/ATS-Postiats#211]
Hi.
There's a function in the ML package to generate a random number, but it seems there's no one to set the seed.
As a result, we need to do something like this to generate a random number:
```ats
staload STDLIB = "libats/ML/SATS/stdlib.sats"
staload LIBC = "libats/libc/SATS/stdlib.sats"
staload TIME = "libats/libc/SATS/time.sats"
staload UN = "prelude/SATS/unsafe.sats"

implement main0 () = () where
{
    val () = $LIBC.srandom($UN.cast {uint} ($TIME.time_get ()))
    val value = $STDLIB.randint(100)
}
```
I think we should have a function in the ML package to do the `srandom` stuff.
Thanks to add it.

**Comment by githwxi** [comment]
This is all C stuff.

You could do something like this:

val () =
$extfcall
(void, "srandom", seed) where
{
val seed = $extfcall(uint, "time", 0)
}

**Comment by antoyo** [comment]
Yeah, I understand that.
But I thought we could do the same as the `randint` function which is a wrapper to the C function.
We could have a `seed` function to hide the unsafe code somehow.
Is it what the ML package is for?

**Comment by githwxi** [comment]
If you like more concise syntax, you can do:

val () = 1*$delay($extval(void, "srandom(time(0))"))
