### ISSUE TITLE
In 'fnx a ... and b', the b function isn't accessible afterwards

### ISSUE THREAD

**Issue by jrfondren** [githwxi/ATS-Postiats#217]
Is this a bug? I don't see where it's stated as an intentional result, although it's clear that the primary use of fnx is mutually recursive internal functions.

Consider:

    #include "share/atspre_staload.hats"

    fnx iseven(n:int):bool =
        if n = 0 then true else isodd(n-1)
    and isodd(n:int):bool =
        if n = 0 then false else iseven(n-1)

    implement main0() = println!("isodd(42) = ", isodd(42))

This fails to compile as `isodd` cannot be found. However, the same exact code with `fun` instead of `fnx` can be compiled, and prints out "isodd(42) = false" as expected -- but presumably without mutual tail-call optimization.

**Comment by githwxi** [comment]
The current implementation only makes the first one available
for use subsequently. If you do need isodd, you have to define isodd
one more time:

```ats
fn isodd(n:int):bool = if n = 0 then false else iseven(n-1)
```
