### ISSUE TITLE
no type error for retained viewtypes when declared outside of a function body

### ISSUE THREAD

**Issue by sparverius** [githwxi/ATS-Postiats#223]
Having programmed with linear types, one might expect the following snippet to result in a type error however, it does not.
```ats
#include "share/atspre_staload.hats"

val x = $list_vt{int}(1)
val y = None_vt{int}()
val s = stream_vt_make_nil()
// ...

implement main0 () = ()

```

Normally, placing the same expression(s) within a function, as illustrated below, results in the expected type error "the linear dynamic variable needs to be consumed but it is preserved with the type ...."

```ats
#include "share/atspre_staload.hats"

fun f () : void = {
  val x = $list_vt{int}(1)
}

implement main0 () = ()
```

In the first snippet, is there something special about the scope that prevents the type error message(s)?

**Comment by githwxi** [comment]
This is a "feature": resources at the top level are not tracked.

**Comment by sparverius** [comment]
Thanks, this makes sense. Just wanted to double check.
