### ISSUE TITLE
ICE: Running into "dead code"

### ISSUE THREAD

**Issue by Istvan91** [githwxi/ATS-Postiats#254]
I managed to hit following "dead code":

```ats
// File pats_trans3_env_dvar.dats line 619
          val () = assertloc (false) in s2e // HX: this should be deadcode!
```

This happened while refactoring and opportunistically trying out some "syntactical shortcut". This is currently the "best" minimal example I managed to come up with:

```ats
// reproduction.sats
typedef extBuffer = $extype"union Buffer"
dataview Buffer_v(l:addr, n:int) = buffer_v(l, n) of (extBuffer @ l)
vtypedef Buffer(l:addr) = (Buffer_v(l, 4096) | ptr l)

fn buffer_init
{l:agz}
(!extBuffer? @ l >> Buffer(l)| ptr l): void = "mac#extbuffer_init"
```
and

```ats
// reproduction.dats
staload test = "reproduction.sats"

implement main0() = let
  var buf: $test.extBuffer with pf_buf
  val () = $test.buffer_init(pf_buf | addr@buf)
in
  ()
end
```

I was not able to reproduce the error when merging the 2 files. When I did so I got a syntax error. It looks like the sats file is parsed differently?

In my original code the solution was to use something like
```ats
fn buffer_init
{l:agz}
(!extBuffer? @ l | ptr l): (Buffer(l) | void) = "mac#extbuffer_init"

// instead of
fn buffer_init
{l:agz}
(!extBuffer? @ l >> Buffer(l)| ptr l): void = "mac#extbuffer_init"
```

Expected Result: Some error message instead of an ICE.

**Comment by githwxi** [comment]
This was due to Buffer(l) not being an at-view:

fn buffer_init
{l:agz}
(!extBuffer? @ l >> Buffer(l)| ptr l): void = "mac#extbuffer_init"

Given my understanding, the type for 'buffer_init' should be given as follows:


fun buffer_init
{l:agz}
(extBuffer? @ l | ptr l): Buffer(l) = "mac#extbuffer_init"
