### ISSUE TITLE
A result type

### ISSUE THREAD

**Issue by okeuday** [githwxi/ATS-Postiats#263]
This information is due to two separate concerns:
- ATS Postiats doesn't appear to have a result type (like [Result in OCaml](https://ocaml.org/api/Result.html) and [Either in Haskell](https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-Either.html))
- A result type, if created in ATS Postiats using `datatype`/`datavtype`, appears to always use malloc in the generated C source code when using `-DATS_MEMALLOC_LIBC`.  Having a common result type can provide an example for reducing malloc use (it seems like option should have the same problem, though I haven't checked).  To reduce malloc usage it seems like type information would need to become less specific in the C struct (using the same struct for all constructors, probably using a union for the variation), which I understand may be undesirable when focused on types and correctness in ATS.  Avoiding malloc looks advantageous for small C structs, though it would require testing and would depend on the C compiler being used.  If it was added to ATS, it would likely want to be an optional feature that was conditional when enabled (based on [`sizeof(struct_t) <= 2*sizeof(struct_t*)`](https://stackoverflow.com/a/30987540) ) for the struct to be returned by value.

In OCaml, `(_, string) result` usage seems relatively normal, to handle errors as strings.
In Haskell, `type Result a = Either String a` also seems normal, for the same error handling type.
However, ATS is closely associated to C and C typically has errors handled as `int != 0`.  I have started using the ATS type:

    datavtype
    result (a:vt@ype+) =
      | Ok (a) of (a)
      | Error (a) of (int)
    vtypedef Result (a:vt@ype) = result(a)

To get the ATS result type to be closer to option, it may want to be:

    datatype result_t0ype_bool_type (a:t@ype+, b:t@ype+, bool) =
      | Ok(a, b, false) of (INV(a))
      | Error(a, b, true) of (INV(b))
    stadef result = result_t0ype_bool_type
    typedef Result (a,b:t0p) = [c:bool] result(a, b, c)
    datavtype result_vt0ype_bool_vtype (a:vt@ype+, b:vt@ype+, bool) =
      | Ok_vt(a, b, false) of (INV(a))
      | Error_vt(a, b, true) of (INV(b))
    stadef result_vt = result_vt0ype_bool_vtype
    vtypedef Result_vt(a,b:vt0p) = [c:bool] result_vt(a, b, c)

**Comment by githwxi** [comment]
I am in the middle of implementing ATS3.
A design for ATS3 should make it very convenient for
people to contribute.

I sincerely hope that you will contribute amply once the time comes.

Cheers!
