### ISSUE TITLE
stropt2stropt1 should be strptr2stropt1

### ISSUE THREAD

**Issue by okeuday** [githwxi/ATS-Postiats#266]
Based on the types involved, it looks like the second function name is wrong (it looks like it should be "strptr2stropt1" instead):
https://github.com/githwxi/ATS-Postiats/blob/7f5bea78c8849e730ca9b89bb513d25674b06ae5/prelude/SATS/CODEGEN/strptr.atxt#L132-L135

**Comment by githwxi** [comment]
Thanks. I fixed it.
